spring:
  application:
    name: jvlang-housekeeping
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  ### 请求编码
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update

### 服务器编码
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088

