server:
  tomcat:
    uri-encoding: UTF-8
  port: 8086

spring:
  jackson:
    #日期格式转换
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  data:
    mongodb:
      uri: mongodb://localhost/jvlang-housekeeping
      database: jvlang-housekeeping


#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0

#logging:
#  level: