spring:
  jackson:
    #日期格式转换
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_ADDR:127.0.0.1:3306}/jvlang-housekeeping?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8&&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: ${DEV_MYSQL_USERNAME:root}
    password: ${DEV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    com.jvlang: DEBUG
    dev.hilla: DEBUG
    com.vaadin: DEBUG
