on:
  push:
    branches: [ "dev_backend" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.0]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev_backend
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: node -v
    - name: Build
      run: |
        npm i
    
    - name: Maven Test
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: chmod +x ./mvnw
    - run: ./mvnw test
  
